import { config } from "dotenv";

config({ path:'.env' });

export const {
    PORT,
    NODE_ENV,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    ARCJET_ENV,
    ARCJET_API_KEY,
    MONGO_URI,
    EMAIL_PORT,
    EMAIL_SECURE,
    EMAIL_HOST,
    EMAIL_USER,
    EMAIL_PASS,
    BASE_URL,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    PUBLISHABLE_KEY,
    SECRET_KEY,
    CONSUMER_KEY,
    CONSUMER_SECRET,
    BUSINESS_SHORT_CODE,
    PASSWORD,
    TIMESTAMPS,
    CHECKOUT_REQUEST_ID,
    PASS_KEY,
    STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET,
} = process.env